- name: archive built charm
  when: charm_build_output.rc == 0
  register: charm_archived
  args:
    chdir: "{{ zuul.project.src_dir }}"
    executable: /bin/bash
  shell: |
    tar -cjf {{ charm_build_name }}-{{ zuul.buildset }}.tar.bz2 -C build/builds/{{ charm_build_name }} . \ &&
      mv {{ charm_build_name }}-{{ zuul.buildset }}.tar.bz2 $HOME/{{ zuul.project.src_dir }}

- name: Upload built charm to swift
  delegate_to: localhost
  when: charm_archived.rc == 0
  zuul_swift_upload:
    cloud: "{{ serverstack_cloud }}"
    partition: "false"
    container: "zuul-built-charms"
    public: "yes"
    prefix: ""
    indexes: "false"
    files:
      - "{{ zuul.project.src_dir }}/{{ charm_build_name }}-{{ zuul.buildset }}.tar.bz2"
    delete_after: "14"
  register: upload_results

- block:
    - name: Return charm to Zuul
      delegate_to: localhost
      zuul_return:
        data:
          zuul:
            artifacts:
            - name: built charm tarball
              type: charm
              url: http://10.245.161.162:80/swift/v1/zuul/artifacts/built_charms/{{ charm_build_name }}-{{ zuul.buildset }}.tar.bz2
    - name: Print upload failures
      debug:
        var: upload_results.upload_failures
  when: upload_results is defined
