- hosts: all
  tasks:
    - name: 'tear down controller'
      command: >
        juju kill-controller -t 120s -y {{ serverstack_cloud.region_name }}-{{ serverstack_cloud.region_name }}
      failed_when: false