- hosts: all
  tasks:
    - name: 'tear down controller'
      command: >
        juju remove-machine --force `seq 0 100`
        timeout 120 juju destroy-controller --destroy-all-models --destroy-storage -y {{ serverstack_cloud.region_name }}-{{ serverstack_cloud.region_name }}
        juju kill-controller -t 60s -y {{ serverstack_cloud.region_name }}-{{ serverstack_cloud.region_name }}
      failed_when: false
