- hosts: all
  tasks:
    - name: 'install crashdump'
      become: true
      snap:
        name: juju-crashdump
        classic: yes
    - name: 'crashdump'
      command: juju-crashdump -o "{{ zuul.executor.log_root }}"