- hosts: all
  tasks:
    - name: 'crashdump'
      shell: juju-crashdump -o "{{ ansible_user_dir }}/zuul-output -m {{ item }}"
      with_lines:
        - juju models | grep zaza-| awk '{gsub(/\*?/,""); print $1}'