- hosts: all
  tasks:
    - name: Create destination for logs
      file:
        path: "{{ zuul.project.src_dir }}/log"
        state: directory
        mode: 0755
    - name: 'crashdump'
      args:
        executable: /bin/bash
      shell: >
        set -o pipefail
        for model in $(juju models | grep zaza- | awk '{gsub(/\*?/,""); print $1}'); do
          juju-crashdump -o "{{ zuul.project.src_dir }}/log" -m $model
        done
      when: not zuul_success | bool
    - name: juju status
      args:
        executable: /bin/bash
      shell: >
        set -o pipefail
        for model in $(juju models | grep zaza- | awk '{gsub(/\*?/,""); print $1}'); do
          juju status -m $model > {{ zuul.project.src_dir }}/log/juju-status.$model.txt
          juju status -m $model --format=yaml > {{ zuul.project.src_dir }}/log/juju-status.$model.yaml
        done
    - name: fetch juju logs
      synchronize:
        dest: "{{ zuul.executor.log_root }}"
        mode: pull
        src: "{{ zuul.project.src_dir }}/log"
        verify_host: true
        owner: no
        group: no
