- hosts: all
  tasks:
    - name: 'crashdump'
      shell: juju-crashdump -o "{{ zuul.executor.log_root }} -m {{ item }}"
      with_lines:
        - juju models | grep zaza-| awk '{gsub(/\*?/,""); print $1}'