- hosts: all
  tasks:
    - name: hack around juju's reluctance to deploy misnamed directories
      copy:
        remote_src: "/home/ubuntu/{{ zuul.project.src_dir }}"
        dest: "/home/ubuntu/{{ zuul.project.src_dir | replace('charm-', '') }}"
    - name: Log what the charm's parent directory looks like
      command: >
        ls -al /home/ubuntu/src/10.245.164.94/openstack
    - name: 'Install Juju'
      command: sudo snap install juju --classic
    - name: Render juju clouds.yaml
      template:
        src: clouds.yaml.j2
        dest: clouds.yaml
    - name: Add cloud
      command: /snap/bin/juju add-cloud --client {{ serverstack_cloud.region_name }} clouds.yaml
    - name: 'render credentials.yaml'
      template:
        src: credentials.yaml.j2
        dest: credentials.yaml
    - name: Add credential
      command: /snap/bin/juju add-credential {{ serverstack_cloud.region_name }} --client -f credentials.yaml
    - name: 'Bootstrap Controller'
      command: /snap/bin/juju bootstrap {{ serverstack_cloud.region_name }}/{{ serverstack_cloud.region_name }}
