- hosts: all
  tasks:
    # setup networking
    - name: get ip
      shell: ip a | grep 10.5 | awk '{print $2}' | awk -F '/' '{print $1}'
      args:
        executable: /bin/bash
      register: ip_out
    - name: set test VIP CIDR
      set_fact:
        network: 172.16.{{ ip_out.stdout.split('.')[-1]}}
        cidr_ext: {{ network }}.0/24
    - debug:
        var: network