- hosts: all
  roles:
    - charm-build
  tasks:
    - name: Check if charm is source charm
      shell: |
        [[ -d {{ zuul.project.src_dir }}/src/src ]]
      args:
        executable: /bin/bash
      register: charm_buildable
      failed_when: false

    - name: archive built charm
      when: charm_build_output.rc == 0
      register: charm_archived
      command: tar -cjf {{ charm_build_name }}-{{ zuul.buildset }}.tar.bz2 -C build/builds/{{ charm_build_name }} .

    - name: Upload built charm to swift
      delegate_to: localhost
      when: charm_archived.rc == 0
      zuul_swift_upload:
        cloud: "{{ serverstack_cloud }}"
        partition: "true"
        container: "zuul"
        public: "yes"
        prefix: "built_charms"
        indexes: "false"
        files:
          - "{{ charm_build_name }}-{{ zuul.buildset }}.tar.bz2"
        delete_after: "14"
      set_fact: charm_uploaded
      tasks:
        - zuul_return:
          data:
            zuul:
              artifacts:
                - name: built charm tarball
                  type: charm
                  url: http://10.245.161.162:80/swift/v1/zuul/artifacts/built_charms/{{ charm_build_name }}-{{ zuul.buildset }}.tar.bz2
