- hosts: all
  tasks:
    - name: 'install weebl-tools'
      become: true
      snap:
        name: weebl-tools
        classic: no
      register: result
      until: result is not failed
      retries: 10
      delay: 10
    - name: 'render credentials.yaml'
      template:
        src: credentials.yaml.j2
        dest: credentials.yaml
    - name: Add credential
      command: /snap/bin/weebl-tools.sqalab environment create --yaml credentials.yaml
