- hosts: all
  tasks:
  - name: 'create tenant name'
    set_fact:
      tenant_project_name: "zosci-test-{{ zuul.job }}-{{ zuul.project.short_name }}-{{ zuul.build }}"
  - name: Purge test tenant
    args:
      executable: /bin/bash
    environment:
      OS_USERNAME: '{{ serverstack_admin.auth.username }}'
      OS_PASSWORD: '{{ serverstack_admin.auth.password }}'
      OS_TENANT_NAME: '{{ serverstack_admin.auth.username }}'
      OS_REGION_NAME: '{{ serverstack_admin.region_name }}'
      OS_AUTH_URL: '{{ serverstack_admin.auth.auth_url }}'
    shell: |
      set -o pipefail
      set -e
      ospurge --verbose --purge-project {{ tenant_project_name }} --admin-role-name=Admin
      openstack project purge --verbose --project {{ tenant_project_name }}
    failed_when: false