- hosts: all
  tasks:
  - name: 'create tenant name'
    set_fact:
      tenant_project_name: "zosci-test-{{ zuul.job }}-{{ zuul.project.short_name }}-{{ zuul.build }}"
  - name: Purge test tenant
    args:
      executable: /bin/bash
    shell: |
      set -o pipefail
      set -e
      export OS_USERNAME={{ serverstack_admin.auth.username }}
      export OS_PASSWORD={{ serverstack_admin.auth.password }}
      export OS_TENANT_NAME={{ serverstack_admin.auth.username }}
      export OS_REGION_NAME={{ serverstack_admin.region_name }}
      export OS_AUTH_URL={{ serverstack_admin.auth.auth_url }}
      ospurge --verbose --purge-project {{ tenant_project_name }} --admin-role-name=Admin
      openstack project purge --verbose --project {{ tenant_project_name }}
    failed_when: false