- name: get ip
  shell: ip a | grep 10.5 | awk '{print $2}' | awk -F '/' '{print $1}'
  args:
    executable: /bin/bash
  register: ip_out
- name: set test VIP CIDR
  set_fact:
    network: 172.16.{{ ip_out.stdout.split('.')[-1] }}
- name: set CIDR ext
  set_fact:
    cidr_ext: "172.16.0.0/16"
- debug:
    var: network
- debug:
    var: cidr_ext
- name: echo environment
  shell: env | grep -v OS_
  args:
    executable: /bin/bash