- name: get ip
  shell: set -o pipefail && ip a | grep 10.5 | awk '{print $2}' | awk -F '/' '{print $1}'
  args:
    executable: /bin/bash
  register: ip_out
- name: set test VIP CIDR
  set_fact:
    network: 172.16.{{ ip_out.stdout.split('.')[-1] }}
- name: set CIDR ext
  set_fact:
    cidr_ext: "172.16.0.0/16"
- debug:
    var: network
- debug:
    var: cidr_ext
- name: echo environment
  shell: set -o pipefail && env | grep -v OS_
  args:
    executable: /bin/bash
- name: check dns
  shell: resolvectl; resolvectl query caipora.serverstack; resolvectl query api.jujucharms.com; host caipora.serverstack 10.245.160.2; host api.jujucharms.com 10.245.160.2; host api.jujucharms.com 10.245.160.1
  args:
    executable: /bin/bash
