# - name: get ip
#   shell: ip a | grep 10.5 | awk '{print $2}' | awk -F '/' '{print $1}'
#   args:
#     executable: /bin/bash
#   register: ip_out
# - name: set test VIP CIDR
#   set_fact:
#     network: 172.16.{{ ip_out.stdout.split('.')[-1] }}
# - name: set CIDR ext
#   set_fact:
#     cidr_ext: "{{ network }}.0/24"
# - debug:
#     var: network
# - debug:
#     var: cidr_ext



- name: build charm
  when: needs_charm_build
  args:
    chdir: "{{ zuul.project.src_dir }}"
  environment: "{{ tox_environment|combine(tox_constraints_env|default({})) }}"
  command: >-
    {{ tox_executable }} -e build
  register: charm_build_output

- name: set built charm path
  when: charm_build_output
  set_fact:
    zuul_work_dir: "{{ zuul.project.src_dir }}/build/builds/{{ charm_build_name }}"
